# Generated by Django 5.2.4 on 2025-07-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('userRol', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField()),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField()),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
