# Generated by Django 5.2.4 on 2025-07-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userRol',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
