# Generated by Django 5.2.4 on 2025-07-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('idCustomField', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('select', 'Selección')], max_length=20)),
                ('options', models.TextField(blank=True, help_text="Solo para campos tipo 'select', separadas por comas.", null=True)),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField(blank=True, null=True)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField(blank=True, null=True)),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacantPosition',
            fields=[
                ('idVacantPosition', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField(blank=True, null=True)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField(blank=True, null=True)),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('idCustomFieldValue', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField(blank=True, null=True)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField(blank=True, null=True)),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.customfield')),
                ('idVacantPosition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_dinamicos', to='HumanResources.vacantposition')),
            ],
        ),
    ]
