# Generated by Django 5.2.4 on 2025-07-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
