# Generated by Django 5.2.4 on 2025-07-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_customfield_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacantposition',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('cerrada', 'Cerrada')], max_length=20),
        ),
    ]
