# Generated by Django 5.2.4 on 2025-07-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_alter_vacantposition_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomField',
            new_name='CustomFieldVacantPosition',
        ),
        migrations.RenameModel(
            old_name='CustomFieldValue',
            new_name='CustomFieldValueVacantPosition',
        ),
    ]
