# Generated by Django 5.2.4 on 2025-07-09 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0004_rename_customfield_customfieldvacantposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('idCandidate', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('firstSurName', models.CharField(max_length=255)),
                ('secondSurName', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField(blank=True, null=True)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField(blank=True, null=True)),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldCandidate',
            fields=[
                ('idCustomField', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('select', 'Selección')], max_length=20)),
                ('options', models.TextField(blank=True, help_text="Solo para campos tipo 'select', separadas por comas.", null=True)),
                ('required', models.BooleanField(default=False)),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField(blank=True, null=True)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField(blank=True, null=True)),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValueCandidate',
            fields=[
                ('idCustomFieldValue', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField(blank=True, null=True)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField(blank=True, null=True)),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.customfieldcandidate')),
                ('idCandidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_dinamicos', to='HumanResources.candidate')),
            ],
        ),
    ]
