# Generated by Django 5.1.5 on 2025-07-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0005_candidate_customfieldcandidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='idVacantPosition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.vacantposition'),
            preserve_default=False,
        ),
    ]
