# Generated by Django 5.1.5 on 2025-07-10 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0006_candidate_idvacantposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacantPositionChecklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField(blank=True, null=True)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField(blank=True, null=True)),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
                ('idVacantPostion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.vacantposition')),
            ],
        ),
    ]
