# Generated by Django 5.1.5 on 2025-07-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0007_vacantpositionchecklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacantpositionchecklist',
            old_name='idVacantPostion',
            new_name='idVacantPosition',
        ),
    ]
