# Generated by Django 5.1.5 on 2025-07-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0008_rename_idvacantpostion_vacantpositionchecklist_idvacantposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvaluecandidate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/candidates/'),
        ),
        migrations.AlterField(
            model_name='customfieldcandidate',
            name='type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('select', 'Selección'), ('file', 'Archivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vacantpositionchecklist',
            name='idVacantPosition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='HumanResources.vacantposition'),
        ),
    ]
