# Generated by Django 5.1.5 on 2025-07-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0010_customfieldvaluevacantposition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvacantposition',
            name='type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('select', 'Selección'), ('file', 'Archivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customfieldvaluecandidate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/candidates/'),
        ),
        migrations.AlterField(
            model_name='customfieldvaluevacantposition',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/vacant_position/'),
        ),
    ]
