# Generated by Django 5.1.5 on 2025-07-22 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldLesson',
            fields=[
                ('idCustomField', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('select', 'Selección'), ('file', 'Archivo')], max_length=20)),
                ('options', models.TextField(blank=True, help_text="Solo para campos tipo 'select', separadas por comas.", null=True)),
                ('required', models.BooleanField(default=False)),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField(blank=True, null=True)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField(blank=True, null=True)),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('idLesson', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('archivada', 'Archivada')], max_length=20)),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField(blank=True, null=True)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField(blank=True, null=True)),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValueLesson',
            fields=[
                ('idCustomFieldValue', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='media/lessons/')),
                ('fdl', models.SmallIntegerField(default=0)),
                ('cbu', models.IntegerField(blank=True, null=True)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('luu', models.IntegerField(blank=True, null=True)),
                ('uat', models.DateTimeField(auto_now=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training.customfieldlesson')),
                ('idLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_dinamicos', to='Training.lesson')),
            ],
        ),
    ]
