# Generated by Django 5.1.5 on 2025-07-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvaluelesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
    ]
